package global.sns.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@DynamoDBTable(tableName = "Books")
@Data
@NoArgsConstructor
public class Book {
    @DynamoDBHashKey(attributeName = "bookId")
    @DynamoDBAutoGeneratedKey
    private String bookId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String genre;
    @DynamoDBAttribute
    private List<Page> pages;
}
